### ISSUE TITLE
Do We Want Option And Result?

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/types#5]
## Summary

This is off the back of a conversation I had with @SiAdcock. [In `apps-rendering`](https://github.com/guardian/apps-rendering/tree/master/src/types) we're using a couple of useful types seen in a number of other languages (Rust, Scala, Elm, Haskell), namely:

- `Option` - value or an absence of a value
- `Result` - value or an error

I think it's only valuable to make these available here if engineers from other teams think they'd be useful. I don't think it's sensible to try and push adoption if they're likely to cause confusion or add complexity that's unwanted.

What do people think? @guardian/dotcom-platform @frankie297 @webb04 @alexduf 

### Option

An `Option<A>` is either a `Some` or a `None`. It has the following methods:

#### `withDefault(a: A): A`

Returns the value if `Some`, otherwise returns `a`. You can think of it as "unwrapping" the `Option`, getting you back a plain value.

```ts
const bylineOne = new Some('CP Scott');
bylineOne.withDefault('Jane Smith'); // Returns 'CP Scott'

const bylineTwo = new None();
bylineTwo.withDefault('Jane Smith'); // Returns 'Jane Smith'
```

#### `fmap(f: A => B): Option<B>`

Also called `map` (we've called it `fmap` for [reasons](https://github.com/guardian/apps-rendering/pull/166)). Applies a function to a `Some`, does nothing to a `None`.

```ts
const creditOne = new Some('Nicéphore Niépce');
creditOne.fmap(name => `Photograph: ${name}`); // Returns Some('Photograph: Nicéphore Niépce')

const creditTwo = new None();
creditTwo.fmap(name => `Photograph: ${name}`); // Returns None()

// All together
credit.fmap(name => `Photograph: ${name}`).withDefault('');
```

#### `andThen(f: A => Option<B>): Option<B>`

Like `fmap` but applies a function that *also* returns an `Option`. Then "unwraps" the result for you so you don't end up with `Option<Option<A>>`.

```ts
type GetUser = number => Option<User>;
type GetUserName = User => Option<string>;

const userId = 1;
const username: Option<string> = getUser(userId).andThen(getUserName);
```

### Result

A `Result<E, A>` is either an `Ok` or an `Err`. It has the following methods:

#### `fmap(f: A => B): Result<E, B>`

Similar to `Option.fmap`. Applies a function to the value in an `Ok`, does nothing to an `Err`.

#### `mapError(f: E => G): Result<G, A>`

The companion to `fmap`. Applies a function to the error in `Err`, does nothing to an `Ok`.

#### `andThen(f: A => Result<E, B>): Result<E, B>`

Similar to `Option.andThen`, applies to a `Result` a function that *also* returns a `Result`, and unwraps them to avoid nested `Result`s. Can be useful for stringing together operations that might fail.

```ts
type RequestUser = number => Result<string, User>;
type GetEmail = User => Result<string, string>;

// Request fails: Err('Network failure')
// Request succeeds, problem accessing email: Err('Email field missing')
// Both succeed: Ok('jane@example.com')
requestUser(id).andThen(getEmail)
```

#### `either(f: E => C, g: A => C): C`

The method for turning a `Result<E, A>` into a plain value. If this is an `Err`, apply the first function to the error value and return the result. If this is an `Ok`, apply the second function to the value and return the result.

```ts
const flakyTaskResult: Result<string, number> = flakyTask(options);

flakyTaskResult.either(
    data => `We got the data! Here it is: ${data}`,
    error => `Uh oh, an error: ${error}`,
)
```

#### `toOption(): Option<A>`

Converts a `Result<E, A>` into an `Option<A>`. If the result is an `Ok` this will be a `Some`, if the result is an `Err` this will be a `None`.

**Comment by alexduf** [comment]
I think it might be worth defining what we want out of this repository first.

It feels to me that the types that define how we model the Guardian's business needs should be separate from the types we define to model a program's execution flow.

So if it does make its way into this repository, it might be worth ensuring we have two separate libraries as they try to address two different things?

**Comment by oliverlloyd** [comment]
I personally like things to be simple. My feeling is the easier it is to consume this lib, then the more it will be used. As a js dev, I find these concepts intimidating so if I have the choice between spending the time to learn them or, you know, just defining my types locally and moving on, if I'm honest I'll probably choose the easy path and stick with what I know.

But that's me. I guess we need to weigh up the doubtless benefits to these things alongside the cost of learning them. Maybe we already have lots of devs on the floor that know this stuff and the cost isn't so bad?

**Comment by SiAdcock** [comment]
I guess once something like this out there, either people use it or they don't. I don't see the harm in publishing it because it probably doesn't require much maintainence.

From my perspective, I've seen this used in apps-rendering and I feel a bit intimidated by it. So if just one codebase is using it, it makes it harder for me, as someone who is unfamiliar with the codebase, to dip into it and make changes. However if this is a useful pattern and other codebases start adopting it, it means it's a thing I ought to learn. Which might be a good thing as it might make me a better programmer!

Regarding @alexduf's point about separating domain-related types (e.g. Pillars) from purely engineering types (e.g. Option), I agree with what @oliverlloyd said in the recent *-Rendering meeting: it's difficult to predict how the library will evolve, so let's just put stuff in here and see what happens.

**Comment by sndrs** [comment]
i'm slightly nervous about adding features to languages and deviating from the spec. this is quite different from a type in a file, or even in a project declaration (where you'd probably expect business types, as defined by @alexduf and @SiAdcock above).

is adding features to the language like this in danger of effectively turning our use of typescript into a superset of typescript? is that sustainable? if it's not, which things should not be added?

e.g. if i'm new to the guardian or projects using this, is it clear where i have to turn to understand what i'm reading? has it helped me complete my task or caught errors?

on the other hand, if we think it's a valuable contribution to typescript, should we propose it upstream to typescript themselves?

**Comment by gtrufitt** [comment]
I can see the value and I do like these types - I think they're just about enough of functional programming to bring value without adding *too* much complexity. Types like `Result` in particular have value.

However, I do think that they do higher the bar to entry for a lot of developers coming to Typescript projects (Typescript sometimes pushing that bar up itself, I often find TS getting in the way personally), and I wonder whether we already have the tools and abstractions to avoid errors without increasing the complexity at the Type and usage level? Further to @sndrs's point - do these help catch errors that were otherwise not going to be caught by Typescript or other tooling? I'm not sure.

I also don't think it makes sense that these sit here in particular - this looks like a generic library on top of TypeScript rather than specific to The Guardian.   That said, if we decide that we want to bring Functional Programming to our Typescript projects, maybe we're better using and contributing to existing projects like https://github.com/gcanti/fp-ts ?

**Comment by JamieB-gu** [comment]
Thanks everyone for taking the time to think about this, these are all great responses! I'll try to add my thoughts to some of the points raised, but please correct me if you think I've got something wrong.

> types that define how we model the Guardian's business needs should be separate from the types we define to model a program's execution flow

> it's difficult to predict how the library will evolve, so let's just put stuff in here and see what happens

I don't feel strongly either way on this, I'm happy to go with whichever approach we decide on.

> As a js dev, I find these concepts intimidating

> I've seen this used in apps-rendering and I feel a bit intimidated by it

This is my concern as well. I don't want to push this style of programming if it's going to hinder people more than it's going to help them. Maybe it would be good to do a workshop session on these data types to figure that out?

> Maybe we already have lots of devs on the floor that know this stuff and the cost isn't so bad?

I hope these things may be more familiar to Scala devs, although happy to be told otherwise. I designed the API to be closer to the Scala/Rust implementations (method calls) than the Haskell/Elm versions (pure function calls) for this reason.

> i'm slightly nervous about adding features to languages and deviating from the spec

I agree with you; specs exist for a reason and increasing cognitive overhead is usually detrimental.

That said, for me at least I find these features reduce the amount I have to remember. These concepts exist across multiple languages and libraries. Therefore, I don't have to deal with JavaScript specific `A | null | undefined` or TypeScript's `{ foo?: "bar" }`, I just have the familiar `Option` and `Result` regardless of what stack I'm working with.

> is adding features to the language like this

I'd like to draw a distinction here between a language feature and a library feature (hopefully not just to be pedantic!). To the best of my understanding, I don't think this has extended TypeScript as a language (I'd probably make a mess if I tried that).

I understand something like [TypeScript's `enum`](https://www.typescriptlang.org/docs/handbook/enums.html) as a *language* feature, because it adds new functionality that it wouldn't be possible to implement otherwise. In contrast, types like [`Option` in Scala](https://www.scala-lang.org/api/current/scala/Option.html) and [`Result` in Rust](https://doc.rust-lang.org/std/result/) are part of the standard libraries. They're built within the bounds of the language and anyone could implement them without altering the language spec.

I view these changes as a small library to help you structure your code, which in other languages would be part of the *standard* library. In the world of JavaScript I don't think this is uncommon. JavaScript famously "doesn't have a standard library", which is why projects like underscore and lodash exist.

> if we think it's a valuable contribution to typescript, should we propose it upstream to typescript themselves?

I'm not too familiar with the stated goals of the TypeScript project. As much as I like this idea, I suspect the response would be that this lies outside these goals, in part because of what I mentioned above.

> they're just about enough of functional programming

I would like to clarify this, because reading through your comment I think the argument is that this functionality is a component of FP (please correct me if I've misinterpreted that)? I would argue that these data types exist independently of the programming paradigm; they can exist in FP, OO or imperative contexts. Rust, for example, is _not_ an FP-focused language, and with Scala I think that depends mostly on the programmer. Haskell and Elm _are_ very much FP languages. These data types exist in the libraries of all of them.

Transitioning towards a more FP approach might be something that we want to do or it might not, but I'd argue that it's a separate goal to what we're trying to achieve here. Is that fair? Please let me know if you think my interpretation of what you said isn't quite right!

> I wonder whether we already have the tools and abstractions to avoid errors

I created these partly because I think we don't 🙂, but that's subjective and it'd be great to hear what people think. My reasoning, in summary:

`Option` - Let me know if you want to discuss this more, but in brief I find `A | null | undefined` difficult to work with. I also prefer the explicitness of `Option` compared with optional arguments and properties (`?`). Worth noting that I don't think I'm alone in this, we previously had another `Option` type implemented by @alexduf, which still exists in [mobile-purchases](https://github.com/guardian/mobile-purchases/blob/b48b12698613c289ab6329c1d60738d516f86961/typescript/src/utils/option.ts).
`Result` - I'm not aware that JS or TS offer something equivalent to this. I typically find you have little way of telling whether a function can fail until it appears in your logs. I also don't find the `throw...catch` model of error handling very robust, but that's a personal opinion and there are many arguments on both sides of this in the industry.

> if we decide that we want to bring Functional Programming to our Typescript projects, maybe we're better using and contributing to existing projects

I think that's a really good point! I don't know the answer but I personally think that's the strongest argument for not creating this library: this functionality may be available elsewhere.

That said, I think there are two issues with this approach:

1. This is not meant to be an attempt to enforce FP on our code. As I mentioned above, I don't think these data types are specific to FP, and shouldn't require adherence to those principles.
2. This functionality was introduced to fix a small pain point in our code. I don't know that it needs to grow any further beyond these two data types. In fact, [when I attempted that](https://github.com/guardian/apps-rendering/pull/63) @alexduf pushed back and I think he was right. Adopting a library like the one you linked I think is a more drastic change?

Apologies for the length of this if you've made it this far, but I like the trend towards open discussions on issues!

**Comment by SiAdcock** [comment]
Interesting addendum: I was just on the Twitter for some unrelated reason, and I plonked a link to this issue. @oliverjash [pointed out](https://twitter.com/OliverJAsh/status/1263422454015373312) that fp-ts tree-shakes well. So if we _only_ use it for [Option](https://gcanti.github.io/fp-ts/modules/Option.ts.html) and [Either](https://gcanti.github.io/fp-ts/modules/Either.ts.html), maybe that's job done?

**Comment by OliverJAsh** [comment]
> if we _only_ use it for [Option](https://gcanti.github.io/fp-ts/modules/Option.ts.html) and [Either](https://gcanti.github.io/fp-ts/modules/Either.ts.html), maybe that's job done?

That's exactly what we do at Unsplash and it's working well for us.

We also use:

- the `Task` type which is just a wrapper around `Promise` to make it lazy
- [RxJS (`Observable`) bindings for fp-ts](https://github.com/gcanti/fp-ts-rxjs)
- [an additional `RemoteData` type](https://github.com/devexperts/remote-data-ts).

If you're still considering whether `Option` is any better than `T | null | undefined`, you may find [this gist useful](https://gist.github.com/OliverJAsh/e6ba59d88f4fd0166e3a4211d7eae2be). I compare `Option` vs non-`Option` in various different logical operations.

Another big selling point of fp-ts: as soon as you start using these "container" types (you are already using `Array` and `Promise`), you'll need ways to compose them. For example, how do I convert `Array<Option<T>>` to `Option<Array<T>>`? fp-ts provides a whole suite of functions to help you with things like that. (In this example we can use `sequence`.)

Also: we're slowly realising that fp-ts can replace nearly all of our usage of Lodash. The types for Lodash are very poor (I've contributed many fixes but still), and fp-ts provides versions of most Lodash functions, with much better types. For example, the `Array` module provides a `filterMap` function, which can replace Lodash's `pickBy`.

**Comment by JamieB-gu** [comment]
> fp-ts

This is fascinating, some of the API is surprisingly similar to what we've come up with (e.g. [`fromNullable`](https://gcanti.github.io/fp-ts/modules/Option.ts.html#fromnullable) and [`fromEither`](https://gcanti.github.io/fp-ts/modules/Option.ts.html#fromeither)), but *much* more comprehensive. I really like some of the convenience functions like [`tryCatch`](https://gcanti.github.io/fp-ts/modules/Option.ts.html#trycatch) and [`lookup`](https://gcanti.github.io/fp-ts/modules/Array.ts.html#lookup) (runtime crashes caused by missing index lookups make me sad 😔). Also `Reader` looks interesting, [our attempt](https://github.com/guardian/apps-rendering/pull/63) to implement that didn't quite get off the ground.

I'd be happy to give this a go, but it would pose some questions:

1. As far as I can tell, this API uses pure function calls rather than methods. What I mean by that is that you would do this:

```ts
const optA = some(4);
const optB = map(x => x + 1, optA);
```

as opposed to this (which is how it looks for our implementation):

```ts
const optA = new Some(4);
const optB = optA.fmap(x => x + 1);
```

I'm happy with either, but I went with the method syntax initially because it seemed to be more familiar to people coming from Scala and possibly also JS (think `Array.map`, `Array.reduce` etc.). Would this cause friction for us?

2. This API uses the more standard/conventional `Either` with `Left` and `Right`. We implemented the, also used but less common, `Result` type with `Ok` and `Err`. `Result` is probably less generic, but this was done because it seemed to cause less confusion for developers. Would this cause friction for us?

3. You mentioned just using `Option` and `Either` from the library and that's all, but I suspect given the size of the API it provides (including things like `Chain` and `Applicative` etc.), and what @OliverJAsh mentions above:

> provides a whole suite of functions to help you with things like that

we'll inevitably start to see it shape more and more of our code. I'm *personally* fine with this, but I'm also mindful of the concerns expressed by @gtrufitt above:

>  I do think that they do higher the bar to entry for a lot of developers coming to Typescript projects

On this I would reiterate that I really like this library and would personally find it beneficial, but I'm cautious of charging ahead and causing problems for other developers who work on these codebases.

**Aside:**

> If you're still considering whether Option is any better than T | null | undefined

I'm already very sold on this, don't worry 🙂

**Comment by OliverJAsh** [comment]
> As far as I can tell, this API uses pure function calls rather than methods.

Just to quickly note: there are a number of good reasons why fp-ts does this. I can't remember them all off the top of my head, but some downsides of classes/methods: they are not serialisable (e.g. you can't/shouldn't put them in Redux state) and the methods are not tree shakeable.

More and more libraries are moving away from methods to "pipeable operators" for [reasons similar to this](https://github.com/ReactiveX/rxjs/blob/b0fe2866989bff76431304ee71a8299d4cc341a6/doc/pipeable-operators.md#why). E.g. [RxJS](https://github.com/ReactiveX/rxjs), [idb-keyval](https://github.com/jakearchibald/idb-keyval), and [Fluture](https://github.com/fluture-js/Fluture).

You would probably do something more like this:

> ```ts
> const optA = some(4);
> const optB = pipe(optA, map(x => x + 1));
> ```

**Comment by SiAdcock** [comment]
Like you, @JamieB-gu, I'm very sold on this approach. The ergonomics of `Option` and `Either` alone are enough to make code more human-readable. After a certain amount of time using them, you'll look back on imperative null checking and wonder how you ever worked that way.

> `Result` is probably less generic, but this was done because it seemed to cause less confusion for developers. Would this cause friction for us?

We could provide a thin wrapper around `Either`? However I don't think friction caused by more generic naming would be so high.

> we'll inevitably start to see it shape more and more of our code.

I agree that more and more features creeping in could be a problem. We could [enforce only a subset of the features](https://eslint.org/docs/rules/no-restricted-imports) and see whether we find ourselves greedily longing for some of those other juicy functions. If we're mindful of the second order of effects of using a library like this (and we clearly are, or, at least, we are _now_) then we can keep checking in with those less familiar with the code to ensure we're making the right choices.

> I do think that they do higher the bar to entry for a lot of developers coming to Typescript projects

> I went with the method syntax initially because it seemed to be more familiar to people coming from Scala and possibly also JS

> I'm cautious of charging ahead and causing problems for other developers who work on these codebases.

I agree that it increases the on-ramp for developers coming from an imperative JavaScript background to  a functional TypeScript approach. I empathise with this argument a lot, I had such a headache getting into TypeScript. I think this was mainly due to the poorly-organised documentation that TypeScript had at the time. The documentation for fp-ts looks a lot easier to follow. As I mentioned earlier, I find code using this approach to be more readable once I understand what it's doing. The use of type parameters even helps me understand how to work with TypeScript at a deeper level.

It would be good to get some Scala-dev and TypeScript novice eyes on this to see whether the friction would be too great: the people who we are trying to accommodate for.

**Comment by JamieB-gu** [comment]
I'm going to close this for now, as these were added in #12, #13 and #14.

If anyone has any further thoughts please continue to comment; either re-open this issue or create a new one!
